apiVersion: v1
kind: Service
metadata:
  name: {{ include "octopub.fullname" . }}
  labels:
    {{- include "octopub.labels" . | nindent 4 }}
  annotations:
{{- range $name, $value := .Values.service.annotations }}
    {{ $name | quote }}: {{ $value | quote }}
{{- end}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "octopub.selectorLabels" . | nindent 4 }}
