apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-development
  annotations:
    codefresh.io/product: octopub
spec:
  project: default
  source:
    repoURL: https://github.com/twerthi/octopub.git
    targetRevision: HEAD
    path: codefresh/local-controlplane/envs/Development
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true

