---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: cf-development
spec:
  encryptedData:
    database-password: AgAi1Akj+KsN5apddhzCf6eVfWtvl9HdJ2DIXfFQf4BzMtX5NuT3Xs5ePnFmUTeKt86hTlJljqjjmuocx2KU3XILZ3kVwb4UV2Dz+6rEBiE6rXU1E3NYRPHYOJmuw1UWQ9znZnZzqHLl6m+/atLoK7pp9l7I2GyGlhrDqqzkWpjkngg0lp2FRatYLJf/X0iHZvfa1y6aYT0/38X0F7sp2NUfuBYMZAFsdoGvnupXCn75DGr6tfO9lmZr2y53dgd+9KC/2Kmyx6L/dvhCo+ObqHY2RzG84Et6TIOkqw9bCm98gxIqASzrQlLwNtus0UBJDxCB8IY4SlSR6yoxdsfcaeOrQ9enMi5ov9FFIHx3RisSpHDmnXwNq5BdCtfoxDJ+dl6P2g1BhUTpPizH7XK3XwtIXvpZ97Z9jbHJJxZJMPx0JEgVTX9/h3LKYamaqFOJJ8bVPvTFq/mdJUFSbZhEeehr77jhZ9Hft1S57uEUZ3YEOZdR9/ZgGcg3M9vc8fYEo6bkVqwdoJoBWH082MUjaJUslfgyShMXGRaTDqNvvMpbVTeH+PxwPi52tWmSfBi80kj7fGXs7ctsNQLrb6nBW7aN3TzHPdUOqe/iTn4RC36q0HV7LMJzDqf0P0hh+Y9V5lBSM2lSYjzgeXmZ8wLMQvKedQ/HNi0g51Bhz4djLWdFG0lYe1fYsC9m5r0dzLdGrOli4VdDPsqT1O+LxBY=
    database-user: AgBgzZQCQuyKnrbJOGFQpdhll+QLN2Mbq57JgWh/Pb2Y+wD6HiWhqDRs7V48x+2WJ3HJk4kQx/UJcBGlSI7HqWNrhQuUVCl2NRh/myd5HZzJmd99AC+y5iLfUbzsbSai4EUhTJ5jGBFDgDxi9EkSPt4kpwUoI6vgZ5h9gcTrFGhtpfJlUlpJzVoXVOaPTgCvWAs+TA0Jp/WGRgj26Dfw2++rKYXRhdR54BVkOvsDzrzUWJbA0lwcKsuiKLRr3kqvmkGyot0lIER+3q4RV5lDSMZD3L05pG39PrkJitI9k5Mb3MFWOHTI5F9iuGgrEZp0LfpXpL5R1+OhoOMAiar+d5lOYuPH4nJdDCPzG8L8nJJz3WB/5QBU4dj1f4xUwTh+PdLvNj+BB8NO0EcaPHrpTLCaYLe7crBEsI90Xwih+dhTLjX6fVKwwqmKIpPXXMAZZOYqoo89UL1pUfbaRq0rUANmW2niMvReGiMMcqPpKXPG8tevqvZQmE9BKwvfYZp7afIjoDz8d3DcVuzrrgftOUnJ5KaMSR6zxn2+4Ee+R02Z3YHRrW2Nk0KanY3rQIhX3tTcIiXhwzBZLqoHCZKUxXpqjmWFHs31xMw5XKDJLC5/a2H4/C71Q0tby+FI02KeYPp3iMihsmBL4dt7/MuTdEC/sFsqVxUqUGQdrU8Yp1ps66JpoTtfxCq0MIWpV8sXfg5cU/18
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: cf-development
