apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- octopub-frontend.yaml

configMapGenerator:
  - name: service-env-vars
    env: variables.properties

generatorOptions:
  disableNameSuffixHash: true