apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-frontend-development
  annotations:
    codefresh.io/product: octopub
spec:
  project: default
  sources:
    - repoURL: https://github.com/twerthi/octopub.git
      targetRevision: HEAD
      path: codefresh/helm/octopub-frontend/development
  destination:
    server: https://kubernetes.default.svc
    namespace: cf-development
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true