apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-secret-test
spec:
  project: default
  source:
     repoURL: https://github.com/twerthi/octopub.git
     targetRevision: HEAD
     path: codefresh/helm/octopub-secret/Test          
  destination:
    server: https://kubernetes.default.svc
    namespace: cf-test
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true