apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-audit-development
  annotations:
    codefresh.io/product: octopub-audit
spec:
  project: default
  sources:
    - repoURL: https://github.com/twerthi/octopub.git
      targetRevision: HEAD
      path: codefresh/helm/octopub-audits-mysql/development
    - repoURL: https://github.com/twerthi/octopub.git
      targetRevision: HEAD
      path: codefresh/helm/octopub-secret/Development          
  destination:
    server: https://kubernetes.default.svc
    namespace: cf-development
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true