name: Build Audits
permissions:
  contents: write
  packages: write
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Audit Microservice
        uses: ./github/java-microservice
        with:
          run_number: ${{ github.run_number }}
          github_repo: ${{ github.repository }}
          github_token: ${{ github.token }}
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
          service_directory: audit-microservice
          github_codefresh_token: ${{ secrets.CF_GITHUB_TOKEN }}
          codefresh_token: ${{ secrets.USER_TOKEN }}
          octopus_server_url: ${{ secrets.OCTOPUS_SERVER_URL }}
          octopus_api_key: ${{ secrets.OCTOPUS_API_KEY }}
          octopus_space: ${{ secrets.OCTOPUS_SPACE }}
